Design Entry;HDL Check||(null)||Checking HDL syntax of 'std_counter.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'std_counter.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'std_counter.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Syntax checking is successful||(null);(null)||(null);(null)
Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98369539||Info: I/O Bank and Globals Assigner detected (7) out of (7) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:aufgabe2
Implementation;Place and Route||(null)||Please refer to the log file for details about 12 Info(s)||aufgabe2_layout_log.log;liberoaction://open_report/file/aufgabe2_layout_log.log||(null);(null)
Implementation;Generate Bitstream;RootName:aufgabe2
Implementation;Generate Bitstream||(null)||Please refer to the log file for details about 1 Info(s)||aufgabe2_generateBitstream.log;liberoaction://open_report/file/aufgabe2_generateBitstream.log||(null);(null)
HelpInfo,D:\Microchip\Libero_SoC_v2022.2\SynplifyPro\lib\html,fpgahelp.qhc,synerrmsg.mp,D:\Microchip\Libero_SoC_v2022.2\SynplifyPro\bin\assistant
